package main

import (
	"fmt"
	"log"
	"net/http"
	"time"
)

const (
	htmlPath = "./files/output"
)

func main() {
	// run server for index.html that generated by generator
	fmt.Println("Running server: http://localhost:8080")
	fmt.Println()
	srv := http.Server{
		Addr:        ":8080",
		ReadTimeout: 5 * time.Second,
		Handler:     http.FileServer(http.Dir(htmlPath)),
	}
	log.Fatal(srv.ListenAndServe())
}
